name: MS Teams Deploy Card

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: Europe/Paris

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: action-logs
          path: ./output.log
